name: build_tox_tests

on: [push, workflow_dispatch]

jobs:
  tox_in_docker:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Build Docker image
        run: make build

      - name: Run tests in Docker container
        run: make test
